### ISSUE TITLE
SocialGAIL: Faithful Crowd Simulation for Social Robot Navigation

### ISSUE THREAD

**Issue by Ashtray4** [William-island/SocialGAIL#1]
您好 我对您的工作非常感兴趣 不知能否提前拜读您的论文"SocialGAIL: Faithful Crowd Simulation for Social Robot Navigation" 非常感谢！

**Comment by William-island** [comment]
能否提供您的邮箱，我通过邮箱发送给您

**Comment by Ashtray4** [comment]
***@***.***，这是我的邮箱。🌹🌹🌹



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 3, 2024 11:02 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [William-island/SocialGAIL] SocialGAIL: Faithful Crowd Simulationfor Social Robot Navigation (Issue #1)




 
能否提供您的邮箱，我通过邮箱发送给您

**Comment by William-island** [comment]
不好意思，github会屏蔽issue的邮箱显示，您能否在您的主页挂上邮箱
![image](https://github.com/William-island/SocialGAIL/assets/56476937/32ae1308-ee1d-4920-9d77-828d8ddd2e91)

**Comment by Ashtray4** [comment]
您好 主页已更新







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "William-island/SocialGAIL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月4日(星期四) 晚上8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [William-island/SocialGAIL] SocialGAIL: Faithful Crowd Simulation for Social Robot Navigation (Issue #1)





 
不好意思，github会屏蔽issue的邮箱显示，您能否在您的主页挂上邮箱
 image.png (view on web)

**Comment by William-island** [comment]
已发送

**Comment by Ashtray4** [comment]
非常感谢！



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 4, 2024 21:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [William-island/SocialGAIL] SocialGAIL: Faithful Crowd Simulationfor Social Robot Navigation (Issue #1)




 
已发送
